name: drone-facerec
dependencies:
  - python=3.6
  - pip: 
    - pillow
    - imutils
    - numpy
    - tensorflow
    - keras
    - dlib>=19.4
    - opencv-python>=3.2
    - sklearn
    - matplotlib    

